kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    username: jcm
    password:
      from_secret: docker_password
    repo: git.jcm.re/jcm/chocobot
    registry: git.jcm.re
