name: build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup buildx
      uses: https://github.com/docker/setup-buildx-action@v2
    - name: login into container registry
      run: |
        BASE64_AUTH=`echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64`
        mkdir -p ~/.docker
        echo "{\"auths\": {\"$CI_REGISTRY\": {\"auth\": \"$BASE64_AUTH\"}}}" > ~/.docker/config.json                
      env:
          CI_REGISTRY: https://git.jcm.re
          CI_REGISTRY_USER: ${{ secrets.REGISTRY_USERNAME }}
          CI_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
    - name: build image
      uses: https://github.com/docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: git.jcm.re/jcm/chocobot:latest
