name: build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup buildx
      uses: https://github.com/docker/setup-buildx-action@v2
    - name: registry login
      uses: docker/login-action@v2
      with:
        registry: git.jcm.re
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: build image
      uses: https://github.com/docker/build-push-action@v4
      with:
        push: true
        tags: git.jcm.re/jcm/chocobot:latest
