name: build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup buildx
      uses: https://github.com/docker/setup-buildx-action@v2
    - name: build image
      uses: https://github.com/docker/build-push-action@v4
      with:
        push: false
        tags: git.jcm.re/jcm/chocobot:latest
