steps:
  build:
    image: ubuntu:noble
    commands:
      - mkdir ./upload
      - ln -s $PWD/upload /out
      - PARALLEL=2 ./scripts/build_libpqxx.sh
  upload:
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
      target: /config/data/files/
      source: upload/
      strip_components: 1
when:
  - event: manual
    evaluate: '(BUILD_LIBPQXX ?? "false") == "true"'
